# Generated by Django 5.1.7 on 2025-04-01 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiffin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiffin_number', models.CharField(max_length=4)),
                ('tiffin_mohalla', models.CharField(max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiffins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
