# Generated by Django 5.1.7 on 2025-04-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
