# Generated by Django 5.1.7 on 2025-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tiffin_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
